#!/bin/sh
mount -o remount,rw /

wget --no-check-certificate -qO- https://github.com/ -O /tmp/x28.tgz

rm -rf /mnt/data/etc/tzcfg/update_config
cp /mnt/data/etc/tzcfg/main_config /mnt/data/etc/tzcfg/main_config.bk
cp /tzwww/cgi-bin/http.cgi /tzwww/cgi-bin/http.cgi.bk
cp /usr/bin/mtk_netagent /usr/bin/mtk_netagent.bk
kill `ps | grep mtk_netagent | awk '{print $1}'`
tar -xzvf /tmp/x28.tgz -C /
/usr/bin/mtk_netagent &
sleep 3
reboot
exit
fi
